### ISSUE TITLE
Error when running make render command

### ISSUE THREAD

**Issue by colmjude** [digital-land/specification#2]
If I run `make render` I get the following error

> python3 bin/render.py
Traceback (most recent call last):
  File "bin/render.py", line 179, in <module>
    template + ".html", "%s/%s/index.html" % (template, name), name, item
  File "bin/render.py", line 33, in render
    f.write(env.get_template(template).render(tables=tables, name=name, item=item))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 8602: ordinal not in range(128)
make: *** [render] Error 1

Whereas if I run `python bin/render.py` from the terminal it works fine. Any ideas?

**Comment by colmjude** [comment]
Fixed by 9857800ae
